[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python init_db.py"]

[start]
cmd = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT run:app"
